export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_PASS = "PRODUCT_PASS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const PRODUCT_PASS_DETAILS = "PRODUCT_PASS_DETAILS";
export const PRODUCT_FAIL_DETAILS = "PRODUCT_FAIL_DETAILS";
export const PRODUCT_RESET_DETAILS = "PRODUCT_FAIL_DETAILS";
